import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-rjit',
  templateUrl: './rjit.component.html',
  styleUrls: ['./rjit.component.css']
})
export class RjitComponent implements OnInit {
  resData;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
  newsdata;
  constructor(private http:HttpClient) { }
  
  ngOnInit() {
    const url="http://127.0.0.1:8000/api/allData";
    this.http.get(url).subscribe(res=>{   //data store
      console.log(res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // this.resData=res;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // this.newsdata=this.resData.user;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // console.log(this.newsdata);
    })
  }

}
